Gemfile
Gemfile.lock
app/assets/stylesheets/application_cms.css.scss
app/assets/stylesheets/outdated.css.scss
app/controllers/outdated_controller.rb
app/mailers/admin_mailer.rb
app/models/outdated_event_report.rb
app/views/application/_admin_bar.html.haml
app/views/outdated/index.html.haml
config/routes.rb
spec/features/csv_import_spec.rb
spec/features/outdated_events_spec.rb
spec/rails_helper.rb
spec/support/macros/feature_auth_helper.rb

Page for viewing outdated events

outdated page

---

app/assets/stylesheets/listings.css.scss
app/views/website/_listing_navigation.html.haml

I'm not a Ruby person so not sure if this compiles 😂Here's screenshots from fiddling with it in Chrome though:

Adds an LLX advert and fixes alignment of social buttons

---

config/application.yml.example
config/initializers/constants.rb

Duncan, I've made this hack - quick and dirty but might work for the purposes of collaborating on the site. Haven't been able to test locally because of xcode issues.

Add second user to list of LOGINS and another environment variable

---

Procfile

https://devcenter.heroku.com/articles/release-phase#specifying-release-phase-tasks

(chore) Run migrations on each release

---

.travis.yml

We'll manage deploys to production with heroku pipelines

Set up Travis to auto-deploy to staging

---

Gemfile
Gemfile.lock
app/controllers/website_controller.rb
app/views/website/privacy.html
config/routes.rb
spec/system/legal_policies_spec.rb

This is required in order to use Facebook login, since in theory we could
capture user data.

(feature) Privacy policy

---

.tool-versions
README.md
bin/setup

Update docs accordingly and add Postgres version to the tool-versions
file.

(chore) Create setup script

---

app/controllers/sessions_controller.rb
app/models/login_session.rb
spec/models/login_session_spec.rb
spec/support/system/omniauth_helper.rb

Login isn't working on staging, so perhaps this will help debug

Add logging around Authentication

---

.travis.yml

This gave the message:
$ sudo service postrgesql start
postrgesql: unrecognized service

(fix) typo in Travis config

---

.travis.yml
app/controllers/events_controller.rb
app/controllers/organisers_controller.rb
app/controllers/venues_controller.rb
app/views/organisers/show.html.erb
app/views/outdated/index.html.haml
app/views/venues/show.html.erb
spec/factories.rb
spec/fixtures/vcr_cassettes/geocode_100_club.yml
spec/support/system/auth_helper.rb
spec/system/admins_can_create_events_spec.rb
spec/system/admins_can_create_organisations_spec.rb
spec/system/admins_can_create_venues_spec.rb
spec/system/outdated_events_spec.rb

- system specs for creating:
- event
- organiser
- venue
- cleanup views - remove tab indentation
- cleanup controllers - remove cruft

Add system specs for creation

---

Gemfile

So that when using the console we get all the benefits of pry

(chore) use pry-rails in production

---

app/views/events/_new_or_edit_fields.html.erb
app/views/organisers/_new_or_edit_fields.html.erb
app/views/venues/_new_or_edit_fields.html.erb

Based on feedback from Rowan getting up to speed

(feature) Add more help text

---

.rubocop_todo.yml
spec/models/event_date_functions_spec.rb
spec/models/event_spec.rb

These specs are failing on CI around midnight

(fix) Dates in specs take account of timezone

---

Gemfile.lock

Railties and ActionView
https://github.com/dgmstuart/swing-out-london/network/alert/Gemfile.lock/actionview/open
https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/rubyonrails-security/topics

(chore) upgrade vulnerable gems

---

.rubocop_todo.yml
app/controllers/events_controller.rb
app/models/event.rb
app/presenters/show_event.rb
app/views/events/show.html.haml
lib/dates_string_parser.rb
lib/tasks/modernise_dates.rake
spec/controllers/events_controller_spec.rb
spec/lib/dates_string_parser_spec.rb
spec/models/event_spec.rb
spec/presenters/show_event_spec.rb

A bunch of complexity arises from handling these getting posted in the form data and having to discount them.

Don't show "Weekly"/"Unknown" in date form fields

---

app/controllers/maps_controller.rb
app/helpers/events_helper.rb
app/models/event.rb
app/models/maps/empty_map.rb
app/models/maps/gmaps_map.rb
app/models/maps/socials/dates.rb
app/services/maps/classes/day_parser.rb
app/services/maps/classes/finder_from_venue.rb
app/services/maps/classes/venue_query.rb
app/services/maps/socials/date_parser.rb
app/services/maps/socials/finder_from_venue.rb
app/services/maps/socials/venue_query.rb
app/views/events/_class_listing.html.erb
app/views/maps/_socials_map_info.html.haml
app/views/maps/socials.html.haml
lib/day_names.rb
spec/controllers/maps_controller_spec.rb
spec/factories.rb
spec/models/event_spec.rb
spec/services/maps/socials/date_parser_spec.rb
spec/system/map_spec.rb

A prerequisite for redoing the maps in a more sane way

Refactor: extract classes from MapsController

---

package.json
yarn.lock

Fixes CVE-2019-10744
https://github.com/lodash/lodash/pull/4336

(fix) Upgrade node dependency

---

yarn.lock

yarn upgrade
I'm not sure we're really using these packages?

Upgrade yarn packages

---

app/assets/stylesheets/listings.scss
app/assets/stylesheets/website.scss
app/helpers/page_helper.rb
app/views/website/_listing_navigation.html.haml
app/views/website/_navigation.html.haml
app/views/website/index.html.haml

- Take up less vertical space
- Finesse the copy
- Don't have a big gap after the nav at smaller sizes
- Move the "Please note" to just above the listings.
- Remove unused icon code
- Use path helpers in nav
- Remove unused social media accounts.

Redesign the header layout:

---

app/views/website/about.html.haml
app/views/website/listings_policy.html.haml

- Fix a link to "About lindy"
- refine the copy on the listings policy intro

More copy updates

---

app/controllers/venues_controller.rb
app/views/venues/_new_or_edit_fields.html.erb
app/views/venues/index.html.erb
app/views/venues/show.html.erb
db/migrate/20211202203412_remove_nearest_tube_from_venues.rb
db/schema.rb
spec/system/smoke_spec.rb

This has never been used: it was YAGNI from the beginning.

Remove nearest tube from venues

---

app/helpers/events_helper.rb
app/models/event.rb
app/presenters/show_event.rb
app/views/events/_new_or_edit_fields.html.erb
spec/presenters/show_event_spec.rb
spec/system/admins_can_create_events_spec.rb
spec/system/admins_can_edit_events_spec.rb
spec/system/smoke_spec.rb

After going through creating an event with Amelie I thought this needed
some improvement:
- Add some helpful text to the dropdown
- Strip underscores and capitalise when displaying

Clarify descriptions of event_type field

---

app/assets/stylesheets/listings.scss
app/views/website/_listing_navigation.html.haml

I'm getting annoyed at getting people trying to contact us in other
ways.

Show full email on the homepage

---

app/assets/stylesheets/website.scss
app/helpers/page_helper.rb
app/views/layouts/info.html.haml
app/views/layouts/website.html.haml
app/views/shared/_header_navigation.html.erb
app/views/website/_listing_navigation.html.haml
app/views/website/_navigation.html.erb
app/views/website/_navigation.html.haml

Include a privacy policy link in the footer

---

.stylelintrc.json
app/assets/stylesheets/application_cms.scss
app/assets/stylesheets/application_map.scss
app/assets/stylesheets/base.scss
app/assets/stylesheets/borders.scss
app/assets/stylesheets/cms/csv_import.scss
app/assets/stylesheets/cms/forms.scss
app/assets/stylesheets/colours.scss
app/assets/stylesheets/listings.scss
app/assets/stylesheets/mobile.scss
app/assets/stylesheets/navigation.scss
app/assets/stylesheets/website.scss
package.json
yarn.lock

Normalise CSS styles

---

app/javascript/application/listing.js
app/views/website/index.html.erb
config/initializers/constants.rb

We used to have a twitter widget thing, but that got removed some time
ago.

Remove unused config related to twitter

---

app/assets/stylesheets/cms/forms.scss
app/models/event.rb
app/views/events/_form.html.erb
app/views/organisers/_form.html.erb
app/views/venues/_form.html.erb

As per the Gov.uk options:
https://design-system.service.gov.uk/components/text-input/#hint-text

Move event form help text above fields

---

app/assets/stylesheets/cms/forms.scss
app/helpers/events_helper.rb
app/views/events/_form.html.erb
spec/system/admins_can_create_events_spec.rb
spec/system/admins_can_edit_events_spec.rb
spec/system/smoke_spec.rb

There are only a few options so this makes more sense.

Event type is now Radio buttons

---

app/assets/stylesheets/website/listings.scss
app/controllers/application_controller.rb
app/controllers/occasional_events_controller.rb
app/helpers/listings_rows_helper.rb
app/javascript/application/listing.js
app/models/event.rb
app/presenters/last_updated.rb
app/presenters/occasional_social_listing.rb
app/views/layouts/website.html.erb
app/views/listings/index.html.erb
app/views/occasional_events/index.html.erb
config/initializers/time_formats.rb
config/routes.rb
spec/presenters/last_updated_spec.rb
spec/system/admins_can_list_occasional_events_spec.rb

Rough first version for review.

Occasional events page

---

app/views/admin_mailer/all_in_date.html.haml
app/views/admin_mailer/all_in_date.text
config/application.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb

The mailer got removed a while ago. We don't need actionmailer.

Remove mailer functionality

---

app/assets/stylesheets/shared/buttons.scss
app/helpers/form_actions_helper.rb
app/javascript/application.js
app/javascript/controllers/organiser_link_controller.js
app/views/events/_event_listing_table_row.html.erb
app/views/events/_organiser_link.html.erb
app/views/organisers/index.html.erb
app/views/sessions/new.html.erb
app/views/sessions/new.html.haml
app/views/venues/index.html.erb
package.json
spec/system/admins_can_copy_organiser_link_spec.rb
spec/system/admins_can_delete_events_spec.rb
spec/system/admins_can_delete_organisers_spec.rb
spec/system/admins_can_delete_venues_spec.rb
spec/system/admins_can_disable_account_spec.rb
spec/system/admins_can_log_out_spec.rb
spec/system/organisers_can_edit_events_spec.rb
yarn.lock

Remove UJS

---

Gemfile.lock

Complaints when running specs about outdated chrome version.

Upgrade selenium webdriver to fix chromedriver

---

app/controllers/name_clash_controller.rb
spec/factories.rb
spec/system/admins_can_edit_events_spec.rb

missed these from a previous commit.

Remove event type from specs

---

app/assets/stylesheets/application_cms.scss

This renders slightly differently in safari

Tweak sieve layout

---

app/javascript/maps/init_map.js
app/views/layouts/map.html.erb
config/initializers/city.rb

This only actually shows when there are no venues - otherwise we use the set of
markers to decide the bounds.

Use a different default map center per city

---

config/initializers/city.rb
config/routes.rb
spec/requests/undefined_assets_spec.rb
spec/system/users_can_see_a_map_spec.rb
spec/system/users_can_see_info_pages_spec.rb

This takes us from 94% coverage to 97%

Improve spec coverage

---

.env.example
README.md
app/controllers/application_controller.rb
spec/requests/basic_auth_spec.rb

For work in progress staging (in this case for Bristol)

Protect the whole site with basic auth

---

.env.example
app/views/users/show.html.erb
config/initializers/facebook.rb
config/initializers/omniauth.rb
spec/system/admins_can_create_events_spec.rb
spec/system/admins_can_create_organisations_spec.rb
spec/system/admins_can_create_venues_spec.rb
spec/system/admins_can_delete_events_spec.rb
spec/system/admins_can_delete_organisers_spec.rb
spec/system/admins_can_delete_venues_spec.rb
spec/system/admins_can_disable_account_spec.rb
spec/system/admins_can_edit_events_spec.rb
spec/system/admins_can_list_events_spec.rb
spec/system/admins_can_log_out_spec.rb
spec/system/admins_can_login_spec.rb
spec/system/admins_can_navigate_spec.rb
spec/system/admins_can_see_associated_events_on_venues_spec.rb
spec/system/admins_can_view_an_audit_log_spec.rb
spec/system/organisers_can_edit_events_spec.rb
spec/system/smoke_spec.rb

Extracting the useful stuff from the slack branch.

Login fixes

---

app/views/info/about/_about_us_bristol.md
app/views/info/about/_intro_bristol.md
app/views/info/about/_show_love_bristol.md
app/views/info/about/_swing_dancing_in_bristol.md
app/views/info/listings_policy/_classes_text_bristol.md
app/views/info/listings_policy/_location_text_bristol.md

Will consult with scene in Bristol once we're live and make further updates then.

Additions and edits to Bristol-specific content. 

---

app/validators/valid_social_or_class.rb
spec/factories.rb
spec/support/shared_examples/events/validates_class_and_social.rb

Otherwise the events won't ever be displayed!

Validation: events without a social must be weekly

---

public/google2437b75f2ce2eac7.html
public/googlee3d4fe603f471939.html

We're now verifying the main site using TXT records in the DNS. Not sure
what happens to staging.

Remove google site verification files

---

.env.example
app/controllers/sessions_controller.rb
app/views/sessions/new.html.erb
config/initializers/facebook.rb
spec/support/system/auth_helper.rb
spec/system/editors_can_archive_events_spec.rb
spec/system/editors_can_copy_organiser_link_spec.rb
spec/system/editors_can_create_events_spec.rb
spec/system/editors_can_create_organisers_spec.rb
spec/system/editors_can_create_venues_spec.rb
spec/system/editors_can_delete_events_spec.rb
spec/system/editors_can_delete_organisers_spec.rb
spec/system/editors_can_delete_venues_spec.rb
spec/system/editors_can_disable_account_spec.rb
spec/system/editors_can_edit_events_spec.rb
spec/system/editors_can_edit_organisers_spec.rb
spec/system/editors_can_edit_venues_spec.rb
spec/system/editors_can_list_events_spec.rb
spec/system/editors_can_list_occasional_events_spec.rb
spec/system/editors_can_log_out_spec.rb
spec/system/editors_can_login_spec.rb
spec/system/editors_can_navigate_spec.rb
spec/system/editors_can_see_associated_events_on_venues_spec.rb
spec/system/editors_can_view_an_audit_log_spec.rb

I want to free up "ADMIN_USER_IDS" for privileged users.

Rename ADMIN_USER_IDS => EDITOR_USER_IDS

---

app/services/revoke_login.rb
app/services/user_name.rb
lib/facebook_graph_api/user_api.rb
spec/services/revoke_login_spec.rb
spec/services/user_name_spec.rb
spec/system/smoke_spec.rb
spec/system/users_can_see_a_map_spec.rb

So close to 100% - when we actually use the UserName service, we'll be at 100

Improve test coverage

---

app/controllers/cms_base_controller.rb
app/controllers/sessions_controller.rb
app/models/return_to_session.rb
spec/models/return_to_session_spec.rb
spec/system/editors_can_disable_account_spec.rb
spec/system/editors_can_login_spec.rb

This is a reasonable expectation: that after trying to visit a protected 
page, you end up at that page after authenticating.

Redirect after login

---

app/assets/stylesheets/application_cms.scss
app/assets/stylesheets/cms/account.scss
app/controllers/admin/caches_controller.rb
app/views/admin/caches/show.html.erb
app/views/layouts/cms/_admin_bar.html.erb
app/views/users/show.html.erb
config/routes.rb
spec/system/admins_can_clear_the_cache_spec.rb

Admins can clear the cache

---

.github/workflows/rubyonrails.yml
config/initializers/dartsass.rb

- CSS source maps
- Don't double-build JS in CI
- Update GitHub actions versions

Assets and CI tweaks

---

app/forms/create_event_form.rb
app/forms/edit_event_form.rb
app/validators/dates_string_validator.rb
spec/forms/create_event_form_spec.rb
spec/forms/edit_event_form_spec.rb
spec/models/soldn_time_spec.rb
spec/support/shared_examples/events/form/validates_event_with_dates.rb
spec/support/shared_examples/events/validates_date_string.rb
spec/system/editors_can_create_events_spec.rb
spec/system/editors_can_edit_events_spec.rb
spec/system/smoke_spec.rb

Disallow
- invalid dates
- dates more than two years in the future
- dates in the past when creating
- dates in the distant past when editing

Validate Date strings

---

config/routes.rb
spec/requests/well_known_spec.rb

Some requests are probably hack attempts, but this seems like a
reasonable URL to request.

Handle .well-known/pki-validation

---

app/controllers/listings_controller.rb
app/helpers/listings_helper.rb
app/helpers/map_listings_helper.rb
app/models/event.rb
app/presenters/class_listing.rb
spec/helpers/listings_helper_spec.rb
spec/models/event_spec.rb
spec/presenters/class_listing_spec.rb

Refactor: Extract a ClassListing presenter

---

app/models/venue.rb
config/locales/en.yml
spec/models/venue_spec.rb
spec/support/shared_examples/venues/validates_postcode_is_postcode_like.rb

This doesn't actually check that postcodes are real - just a sanity
check that they're plausible.
Regexp taken from here: https://ideal-postcodes.co.uk/guides/postcode-validation
Note that we don't require postcodes: some events in the past have had
secret venues, and other times we've had to list things as venue TBC.

Do some simple validation of full postcodes

---

Gemfile
Gemfile.lock

https://github.com/teamcapybara/capybara/commit/e2f9f6cc60d622baf27624e5d224d38cc85f551f

WIP Use Capybara from main: handle chromedriver issue

---

app/javascript/application/listing.js

Remove fb share click handler code

---

app/controllers/admin/users_controller.rb
app/models/user.rb
app/presenters/users_listing.rb
app/services/user_name.rb
app/views/admin/users/index.html.erb
app/views/layouts/cms/_admin_bar.html.erb
config/environments/development.rb
config/routes.rb
spec/fixtures/vcr_cassettes/fetch_facebook_names.yml
spec/presenters/users_listing_spec.rb
spec/services/user_name_spec.rb
spec/support/vcr.rb
spec/system/admins_can_manage_users_spec.rb

Currently there's no way to see who owns which facebook App ID token.

Admins can see the names of users

---

app/presenters/show_event.rb
spec/presenters/show_event_spec.rb
spec/system/editors_can_archive_events_spec.rb
spec/system/editors_can_create_events_spec.rb
spec/system/editors_can_edit_events_spec.rb

Decided to just stick to dd/mm/yyyy rather than trying to make a "human"
date.

Display years in first/last date on event/show

---

app/assets/stylesheets/application_cms.scss
app/assets/stylesheets/cms/_admin_bar.scss
app/helpers/cms/navigation_helper.rb
app/views/events/index.html.erb
app/views/layouts/cms/_admin_bar.html.erb
spec/rails_helper.rb
spec/support/system/menu_helper.rb
spec/system/admins_can_manage_users_spec.rb
spec/system/editors_can_delete_organisers_spec.rb
spec/system/editors_can_delete_venues_spec.rb
spec/system/smoke_spec.rb

Now we can make it always sticky.

Make a collapsible menu

---

app/controllers/events_controller.rb
app/presenters/show_event.rb
app/views/events/show.html.erb
spec/presenters/show_event_spec.rb
spec/rails_helper.rb
spec/support/simplecov.rb

Remove unused code

---

db/migrate/20240408125449_make_frequency_non_null_in_events.rb
db/schema.rb
spec/system/editors_can_archive_events_spec.rb

Nothing on production has nil frequency.

Make frequency non nullable in database

---

app/assets/stylesheets/website/_borders.scss
app/assets/stylesheets/website/_map.scss
app/controllers/maps_controller.rb
app/models/maps/classes/days.rb
app/models/maps/socials/dates.rb
app/presenters/maps/classes/menu_day.rb
app/presenters/maps/socials/menu_date.rb
app/views/maps/classes.html.erb
app/views/maps/socials.html.erb

There's no point showing a day or date with no events.

Map: Lowlight days/dates with no events

---

app/assets/stylesheets/website/_map.scss
app/javascript/maps/map.js

Don't make the user click if there's only one choice, and show them the 
item they were looking for even more clearly.

Open info window if only one marker or highlighted

---

app/views/listings/index.html.erb
app/views/maps/_socials_map_info.html.erb

Let's not hardcode 14 days in more places than we need to.

Refactor: extract number of days

---

app/controllers/external_events_controller.rb
app/presenters/event_status.rb
app/views/external_events/edit.html.erb
spec/presenters/event_status_spec.rb
spec/system/organisers_can_edit_events_spec.rb

Communicate whether the event will be listed or not.

Show a message on Organiser event pages

---

spec/system/editors_can_create_events_spec.rb

Definitely need to assert that the server is done before checking the
database separately.

Fix more speedy specs
