dgmstuart/swing-out-london

Gemfile, Gemfile.lock
- Alphabetise gems in a single block
- Move testing-only gems out of the dev/test block
- Move development-only gems out of the dev/test block
- Add "require false" to some gems which recommend that
- Remove binding_of_caller - it was an extension for better_errors
- Remove awesome-print - I don't use this
=> (chore) reorganise Gemfile

.gitignore, Gemfile, Gemfile.lock, spec/factories.rb, spec/rails_helper.rb, spec/spec_helper.rb
There was some outdated config and a gem which we could do with cleaning
up before the next feature.
=> Various bits of testing cleanup

.env.example, .rubocop.yml, config/initializers/omniauth.rb, lib/omniauth_test_response_builder.rb, spec/lib/omniauth_test_response_builder_spec.rb, spec/support/system/omniauth_helper.rb
Now that we're using data from the auth hash, we can't rely on the
default omniauth test hash anymore.
=> Use a realistic auth hash in development

app/controllers/events_controller.rb, app/models/event.rb, app/models/events_swing_cancellation.rb, app/models/events_swing_date.rb, app/presenters/last_update.rb, app/views/events/_event_listing_table.html.haml, app/views/events/_event_listing_table_row.html.haml, db/migrate/20181114233827_add_primary_key_to_events_swing_dates.rb, db/migrate/20181114235445_add_primary_key_to_events_swing_cancellations.rb, db/schema.rb, spec/presenters/last_update_spec.rb
Previously we were caching the whole action, which meant that the username
of the currently logged in user was cached between different user sessions.
Instead let's use fragment caching on the individual rows of the event list
in the admin area. This is also MUCH faster to regenerate, since it's not
rebuilding the whole page every time there's an update - just the rows
which have changed.
=> FIX: Replace action cache with Fragment cache

app/views/audit_logs/show.html.haml
If only dates were changed, this doesn't show up in the changes -
instead it's stored in the comment field
=> (fix) Add dates to audit log

app/views/layouts/map.html.haml, config/initializers/gmaps4rails.rb
We're using an oooooooold version of Gmaps4Rails, from a time when not
everyone was using the asset pipeline, so Gmaps4Rails looked at some Rails
configuration options to see if we were using it, and if we are it doesn't
explicitly try and load any javascripts in the page: it assumes that
they'll be loaded in the pipeline.
In the upgrade to Rails5, that isn't any longer a valid check for the asset
pipeline (the config option it was using no longer exists), so we
monkeypatch that function to always return true instead.
=> (fix) Tell Gmaps4Rails we use the asset pipeline

.rubocop.yml, Gemfile, Gemfile.lock, app/assets/stylesheets/listings.scss, app/controllers/website_controller.rb, app/models/advert.rb, app/views/website/_advert.html.haml, app/views/website/_listing_navigation.html.haml, spec/models/advert_spec.rb, spec/system/advertising_spec.rb
- Based on the previous implementation of the LLX advert from f2ecaba
- Configure ads using environment variables
- When no ad is configured, show the fallback "advertise here" message
- The non-semantic div here is required for padding - if the padding is
done on the anchor element directly then the hover style appears at
the bottom of the box rather than just below the text.
- Extract to a partial
- Extract Advert to a model object - it should be easy to replace this
with an ActiveRecord model in future.
=> (feature) Conditionally display an advert unit

app/presenters/show_event.rb, spec/presenters/show_event_spec.rb, spec/system/admins_can_navigate_spec.rb
The path helpers call to_param on the target object, which in this case
returned the ShowEvent instance as a string. Delegating to_param to the
event allows the path helpers to work.
=> (fix) path helpers work with ShowEvent

Gemfile, Gemfile.lock, app/assets/stylesheets/application_cms.scss, app/assets/stylesheets/cms/forms.scss, app/controllers/venues_controller.rb, app/helpers/venues_helper.rb, app/models/venue.rb, app/presenters/associated_event.rb, app/services/event_summarizer.rb, app/views/venues/edit.html.erb, app/views/venues/index.html.erb, app/views/venues/show.html.erb, spec/models/venue_spec.rb, spec/presenters/associated_event_spec.rb, spec/services/event_summarizer_spec.rb, spec/support/shoulda_matchers.rb, spec/system/admins_can_create_events_spec.rb, spec/system/admins_can_delete_venues_spec.rb, spec/system/admins_can_see_associated_events_on_venues_spec.rb
Raise an exception if we try to delete a venue which has associated events.
This is kind of a blunt instrument since it doesn't tell the editing user
why they're getting an error, but it keeps us safe.
Previously on production we've deleted venues with live associated events
and this has caused the back-end to become unusable:
https://swingoutlondon.freshdesk.com/a/tickets/791
https://swingoutlondon.slack.com/archives/CEL0CHLLD/p1551782023011300
(feature) Show associated events on venues
Since it's not possible to delete venues with associated events, we should
display those events on the venues.
=> (fix) Raise if deleting venue with events

app/helpers/form_actions_helper.rb, app/helpers/venues_helper.rb, app/models/organiser.rb, app/views/organisers/edit.html.erb, app/views/organisers/index.html.erb, app/views/organisers/show.html.erb, spec/models/organiser_spec.rb, spec/system/admins_can_delete_organisers_spec.rb
This hasn't happened, but would probably break things.
Exactly the same pattern as for venues.
=> (fix) disable deletion of Organisers with events

app/views/layouts/website.html.haml
Make sure that when the banner displays, it doesn't cover the site title
=> Add non-semantic padding to banner

app/helpers/listings_helper.rb, spec/system/smoke_spec.rb
The issue is that school_name can be plain text, but can also be text
wrapped in an abbr tag (for the abbreviated name). String interpolation
converts that tag to raw text and the tags get rendered as text in the
page.
This is kind of annoying: it feels like there should be a way to do
something similar to join(' ') but with concat.
The alternatives are:
Build everything as a string and then use `raw` to have it display
properly, feels more natural but also like bad practice
Or
Use capture/concat everywhere and kind of simulate writing html: in some
ways this is clean, but it's not at all easy to see what the result of
it all is.
=> Fix: display of listing info

app/models/organiser.rb, spec/models/organiser_spec.rb, spec/system/admins_can_create_organisations_spec.rb
https://rollbar.com/swingoutlondon/SOLDN/items/81/
The issue is that we have a unique index in Postgres on shortname (maybe
not really needed?), and that allows multiple nil records, but not
multiple empty strings.
Somehow the way the other SOLDN editors are working means that sometimes
when this field is blank it submits an empty string, so we've gotten a
uniqueness error in production.
I don't see a super good fix for this, but overriding the setter method
for shortname so that we always set nil if the input is an empty string
does the job.
=> Fix: Organisers can handle empty shortnames

config/environments/production.rb
Sendgrid no longer supports username/password
https://sendgrid.com/docs/for-developers/sending-email/authentication/#basic-authentication
=> Use API key for sendgrid

config/environments/production.rb
https://github.com/petergoldstein/dalli/blob/main/3.0-Upgrade.md
In particular, we need to use Rails' built in mem_cache_store since
dalli_store has been removed.
=> Previously we blindly updated the Dalli gem, but Dalli 3 has some changes:

Gemfile, Gemfile.lock
Needed for the caching configuration we've specified in production.rb
Didn't find out about this until I tried to deploy.
Also move dalli to the production group - I think that's the only place
it's used?
=> Add connection pool gem

app/models/event.rb, app/views/events/_new_or_edit_fields.html.erb, spec/models/event_spec.rb, spec/system/admins_can_create_events_spec.rb, spec/system/map_spec.rb
The title is what we display in the listing. Currently we're silently
not displaying these, which is unexpected in the main listing, and looks
broken in the map.
=> Enforce: Events with socials must have a title

Gemfile, Gemfile.lock, spec/rails_helper.rb, spec/support/system/auth_helper.rb, spec/support/system/drivers.rb, spec/support/webmock.rb
So it turns out we weren't ever running specs with js turned on, and the
code we had for doing so didn't work: got complaints about chromedriver
versions being incompatible with chrome.
The latest way to install these drivers seems to be the webdrivers gem.
For some reason the drivers try to call out to a chrome storage thing. I
don't really understand that but I saw a github issue which seemed to
suggest that it was fine to just let it call out.
While we're at it, move code related to drivers into its own file.
=> Switch to webdrivers

Rakefile
We need to actually look at the return code of the stylelint script in
ruby - otherwise ruby is like "Well I successfully sent that command to
the system, so I guess that's success?"
=> Stylelint failures should fail the build

app/models/event.rb, spec/system/admins_can_archive_events_spec.rb
In 89d295b I removed the prev_date method, mistakenly thinking it wasn't
used. As a result, archiving events was broken.
Now (since Rails 5.2?) we have this neat "prev_occurring" method which does
the same thing natively.
=> Fix: archiving events

Gemfile, Gemfile.lock, app/models/event.rb, app/models/organiser.rb, app/models/venue.rb, spec/models/event_spec.rb, spec/models/organiser_spec.rb, spec/models/venue_spec.rb
Some events with leading whitespace in the name exist in the database.
Not sure if it's actually causing any real problems, but it seems like a
good idea to prevent this.
=> Strip attributes before saving

app/assets/stylesheets/cms/forms.scss, app/assets/stylesheets/shared/base.scss, app/javascript/application_cms.js, app/views/events/_form.html.erb, app/views/events/show.html.haml, config/locales/en.yml, package.json, spec/rails_helper.rb, spec/support/system/form_helper.rb, spec/system/admins_can_create_events_spec.rb, spec/system/admins_can_edit_events_spec.rb, spec/system/smoke_spec.rb
:pushpin: https://trello.com/c/LP7OfzuK
The class style field was a little unintuitive before: leaving it blank as
the default. Now we show that default more clearly using radio buttons.
=> A better approach to the "class style" field

app/javascript/application_cms.js
This is the behaviour on the other dropdowns. I'm not sure why this one was different - maybe with the idea that the other two dropdowns are optional but this one is required.
But the reason for allowing blank is that if you empty the text field, then you'll implicitly be selecting the first venue in the list, which is obviously incorrect.
=> Allow selecting no venue

app/models/event.rb, db/migrate/20220928222048_remove_shortname_from_events.rb, db/schema.rb, spec/models/event_spec.rb
This was used originally to have a quick way to find events eg. something like
events/edit/rr
...for red rhythm.
I think this was motivated by a "we have data so let's record it" kind of thinking: RR was how me and my friends would refer to this event in text.
But it hasn't been used in many years and it seems that the feature using it was removed a while back.
This is the list of shortnames at the time of removal:
[id, title, shortname]
[8, "Blitz Party", "blitz"],
[9, "Swing Pit", "pit"],
[10, "Saturday Night Swing Club", "snscfirefly"],
[14, "Rock a hula", "rockahula"],
[18, "Swing Den East (Beginner social)", "swingden"], [21, "Swing Patrol", "spoldst"],
[22, "Black Cotton Club", "blackcotton"],
[27, "Mouthful O'Jam", "mfoj"],
[33, "Book Club Blues", "bcb"],
[42, "A-Train", "atrain"], …
=> Remove event shortname

app/assets/stylesheets/cms/forms.scss, app/views/events/_form.html.erb, app/views/external_events/edit.html.erb, config/locales/en.yml, spec/system/admins_can_create_events_spec.rb, spec/system/admins_can_edit_events_spec.rb, spec/system/organisers_can_edit_events_spec.rb, spec/system/smoke_spec.rb
:pushpin: https://trello.com/c/ybXdPkGf/72-change-hint-text-on-date-entry-fields-to-reduce-chance-of-user-misunderstanding-include-example
Change hint text on date entry fields to reduce chance of user
misunderstanding, include example
Users on the new edit link may not understand the dates field, although
the hint text already explains the date formatting a worked example
might be easier. We can't afford to have the listing/site break because
they've put some nonsense in this field, so it reduces the risk.
=> Improve dates help text

app/models/event.rb, spec/factories.rb, spec/models/event_spec.rb, spec/system/admins_can_edit_events_spec.rb
We're expecting this to be the case in several places in order to
display classes with some information - otherwise there's really nothing
to identify them apart from the location.
=> Enforce that classes have organisers

app/views/external_events/edit.html.erb, spec/system/organisers_can_edit_events_spec.rb
We're settling on events being pretty much weekly or occasional - so let's
reflect that here.
Weekly events shouldn't have a dates box, since they can't use it anyway.
=> Add "Frequency" to external events page

app/javascript/application/listing.js
Turns out this _is_ actually being used for the "please donate" box.
=> Add twitter analytics event code back

app/assets/stylesheets/website/map.scss, app/controllers/maps_controller.rb, app/views/maps/classes.html.haml, app/views/maps/socials.html.erb, spec/controllers/maps_controller_spec.rb, spec/system/users_can_see_a_map_spec.rb
The idea originally was to show a message to users who followed links to old dates or days, explaining why we can't show that date.
This fundamentally doesn't work since the page is cached, so in the scenario where an admin makes an update which results in a flash message about eg. a venue being updated, then visits the map and gets a fresh page, then that flash message gets cached for any users viewing the page after them.
=> Remove Map flash

app/javascript/application_cms.js, app/views/layouts/organiser.html.erb
The JS was restricted to only run on the event form pages, but is
actually needed on the external events page as well.
Let's take a different approach: run the functions everywhere, but do
nothing if the element isn't in the page.
=> Fix JS on external event page

app/assets/stylesheets/cms/forms.scss, app/javascript/controllers/event_frequency_controller.js, app/javascript/controllers/index.js, app/models/event.rb, app/presenters/show_event.rb, app/views/events/_event_listing_table_row.html.erb, app/views/events/_form.html.erb, app/views/events/_organiser_link.html.erb, app/views/events/index.html.erb, app/views/events/show.html.haml, spec/factories.rb, spec/models/event_spec.rb, spec/presenters/show_event_spec.rb, spec/system/admins_can_create_events_spec.rb, spec/system/admins_can_edit_events_spec.rb, spec/system/admins_can_list_events_spec.rb, spec/system/smoke_spec.rb
We've decided to switch to only tracking frequency as being weekly or 
non-weekly, since this is the only distinction which is actually used.
Show/hide the date or day fields appropriately and add some validations to
make sure we still have data integrity.
=> Show dates or day based on frequency

app/views/layouts/application.html.erb, config/environments/production.rb
public_file_server is supposed to be for development (serve assets from
the /public directory) but for some reason heroku has
RAILS_SERVE_STATIC_FILES on:
https://devcenter.heroku.com/changelog-items/617
Which is... whatever, but has the result of not setting any cache
headers. Google lighthouse complains about this, though my browser seems
to be always loading them from disk anyway.
These headers are the visible on assets run locally (where
RAILS_SERVE_STATIC_FILES is false).
=> Set cache headers on assets

app/javascript/application/listing.js, app/views/listings/_advert.html.erb, app/views/listings/_advert.html.haml, spec/system/users_can_see_adverts_spec.rb
With Google Analytics 4, most link clicks are tracked automatically, so we
don't need to attach events manually.
These `_gaq.push` things are no longer supported - we get errors when these
events fire:
listing.js:36 Uncaught ReferenceError: _gaq is not defined
at HTMLAnchorElement.<anonymous>
The only thing that needs to be done is to set a class on the ad link so 
that we can identify it.
I've set up a click report here:
https://analytics.google.com/analytics/web/#/analysis/p359226015/edit/bGLhChheTZCKyRszYcEd8A
=> Use GA4 analytics link click tracking

Gemfile, Gemfile.lock, spec/support/system/drivers.rb
Got errors about chrome in specs:
Webdrivers::VersionError:
Unable to find latest point release version for 115.0.5790. You appear to be using a non-production version of Chrome.
...Then after upgrading the `webdrivers` gem, got this message:
Webdrivers gem update options
*****************************
Selenium itself now manages drivers by default: https://www.selenium.dev/documentation/selenium_manager
* If you are using Ruby 3+ — please update to Selenium 4.11+ and stop requiring this gem
* If you are using Ruby 2.6+ and Selenium 4.0+ — this version will work for now
* If you use Ruby < 2.6 or Selenium 3, a 6.0 version of this gem with additional support is planned
Upgrading selenium-webdriver and removing my locally Homebrew-installed
version of chromedriver resolved this issue.
=> Remove defunct webdrivers gem

app/controllers/events_controller.rb, app/controllers/name_clash_controller.rb, app/forms/create_event_form.rb, app/forms/edit_event_form.rb, app/helpers/events_helper.rb, app/models/event.rb, app/presenters/show_event.rb, app/views/events/_form.html.erb, spec/form_spec_helper.rb, spec/forms/create_event_form_spec.rb, spec/forms/edit_event_form_spec.rb, spec/models/event_spec.rb, spec/presenters/show_event_spec.rb, spec/system/admins_can_create_events_spec.rb, spec/system/admins_can_edit_events_spec.rb, spec/system/smoke_spec.rb
This hasn't actually been used by anything since we removed the Gig
label and the separate section of the events list.
This is preliminary to changing the approach for the event form to
show/hide different fields.
=> Remove "Event type"

app/assets/stylesheets/cms/forms.scss
Previously this broke the layout for radio buttons since they're
displayed inline, but get wrapped in a div (with a class of
field_with_errors) so got displayed on the next line.
Show a red border while we're at it.
BEFORE:
AFTER:
=> Fix: Display nicely when forms break

app/javascript/application/listing.js
These should have been removed in ad54f69, which moved to Google
Analytics 4 link tracking and removed these methods.
=> Remove unused analytics events js

app/assets/stylesheets/application_cms.scss, app/views/events/_event_listing_table_row.html.erb
- somehow the actions were overlaying the main table. Use a button
instead and stop trying to generate a fixed-width table
- Make the filter bigger and add some padding around it.
- Stop hiding columns - we're fine with scrolling.
- Try to have fewer constraints on column width
=> Improve/fix editing experience on mobile:

Procfile, bin/setup, lib/tasks/release.rake
The issue here is that Heroku always tries to run rake db:migrate even
on a completely fresh install. But I'm not trying to maintain the
migrations so that they can be run completely from scratch - instead the
approach is to run rake db:schema:load to create the database, and then
to run `rake db:migrate` for subsequent releases.
This rake task (modified from
https://gist.github.com/stevenharman/98576bf49b050b9e59fb26626b7cceff?permalink_comment_id=4332071#gistcomment-4332071)
achieves this.
=> Run db:schema:load on initial deploy

app/controllers/listings_controller.rb, app/controllers/maps_controller.rb, config/environments/test.rb
This is to ensure that we exercise the cache keys in tests. Maybe this
is a bad idea. I'm not sure exactly what what config option enables.
=> Enable controller caching in test

app/models/config.rb, app/models/info_page.rb, spec/models/config_spec.rb, spec/models/info_page_spec.rb, spec/system/users_can_see_info_pages_spec.rb
"config" as a name is maybe a bit too general, since this only deals
with YAML files, but I don't want to have the file type in the name
either.
=> Cover InfoPage with specs

app/forms/create_event_form.rb, app/forms/edit_event_form.rb, app/models/event.rb, app/validators/form/valid_event_with_dates.rb, app/validators/valid_weekly_event.rb, spec/forms/create_event_form_spec.rb, spec/forms/edit_event_form_spec.rb, spec/models/event_spec.rb, spec/support/shared_examples/events/form/validates_event_with_dates.rb, spec/support/shared_examples/events/validates_event_with_dates.rb
We don't want weekly events to have dates - they probably won't be used,
but it adds confusion and we can't be as confident as we'd like to be.
The issue here was that a) we weren't testing this validation and b)
it needs to be different for the model and the form objects:
For the form objects, dates are a string. At the moment we're not
actually doing any validation on that string, but we want to require the
field to be empty if it's weekly
For the model, a `dates` method exists, but it's the tip of a very messy
iceberg related to the insane way that dates are managed.
Instead the thing that we care about is whether there are any SwingDate
records associated with the Event.
Actually I'm not 100% sure about this, since SwingDate is a separate
model, so Events can become invalid by adding …
=> Fix: properly apply "weekly can't have dates"

config/initializers/omniauth.rb
Previously I made it so that we _either_ configure the OmniAuth
provider _or_ set it up in test mode.
But without configuring the provider, there's no auth link to POST to!
I guess it doesn't actually need real values in order to work: nil is
fine.
=> Fix development login

app/controllers/external_events_controller.rb, spec/system/organisers_can_edit_events_spec.rb
When an organiser link doesn’t work (eg. because it’s been refreshed, or
there’s a typo) currently we bounce them to the homepage, which is a
confusing experience.
Instead we should show them the Not Found page.
=> Bad organiser links show 404 instead of root

app/assets/stylesheets/shared/base.scss, app/views/info/about/_colophon.md, app/views/layouts/application.html.erb
Jost is pretty close to Futura, but I'm not quite confident enough to
switch to using it as the primary font.
Also not feeling like paying for a Futura license.
=> Use Jost through Google Fonts as a Futura fallback

app/views/maps/classes.html.erb
Otherwise it just says "Swing Out London's Lindy Map:" on the SERP
=> Fix title on map classes page

config/routes.rb
New Facebook shares correctly get the new image, but for some reason we
have a bunch of hits from Facebook requesting the old url, which was
just /swingoutlondon_og.png. This is the User Agent:
facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)
Scraping the page from this URL was what made sharing work correctly,
but maybe Facebook has other caches for other uses somewhere:
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.swingoutlondon.co.uk
Not sure what would be impacted - old share links?
Whatever: let's just redirect them to the new image URL.
=> Redirect old OpenGraph image requests

app/controllers/maps_controller.rb
This is for the sake of webcrawlers. It seems like with 302, they'll
keep checking back to see if it's changed, but 301 is a stronger signal
that they don't need to keep checking (or at least to do so less
frequently).
=> Map socials expired dates redirect with 301

spec/system/editors_can_archive_events_spec.rb
The issue here is that sometimes the event names generated by faker
include the word "Show".
In this case, with the seed 37153, the event generated for the middle
spec for "Archive" was "Dr Low's Medicine Show", and since that was the
first link in the page containing the text "Show", that's the link which
got clicked, and then failed since the URLs aren't real URLs.
=> Fix failing spec when clicking "Show"

spec/lib/dates_string_parser_spec.rb, spec/models/login_session_spec.rb, spec/models/return_to_session_spec.rb, spec/models/soldn_time_spec.rb, spec/presenters/map/social_listing_spec.rb, spec/presenters/postcode_spec.rb, spec/presenters/show_event_spec.rb, spec/presenters/social_listing_spec.rb, spec/services/event_params_commenter_spec.rb, spec/services/event_summarizer_spec.rb, spec/services/socials_listings_spec.rb, spec/support/time_formats_helper.rb, spec/system/smoke_spec.rb
Rails 7.1 somehow doesn't play nicely here. Got a lot of "Stack level
too deep" errors. I guess because time helpers are doing something more
basic than Timecop - just stubbing the time classes. The individual
specs succeeded, but running the whole file several of them fail.
Also for some reason we only now need to require "active_support" before
using modules (supposedly it's always been required: https://guides.rubyonrails.org/active_support_core_extensions.html#stand-alone-active-support)
Also the definition of to_date now relies on blank? I guess?
=> Use Timecop in SOLDNTime spec

README.md, app/assets/stylesheets/application_cms.scss
Mostly this is documenting that a buildpack is needed on Heroku
=> Fix CSS build on staging

app/validators/dates_string_validator.rb, lib/dates_string_parser.rb, spec/support/shared_examples/events/validates_date_string.rb
In the scenario where a user adds eg:
12/02/2024,12/02/2024
… that’s probably a mistake - maybe they meant to add:
12/02/2024,12/03/2024
…so we should show a validation error.
Use a Set since it's optimised for uniqueness so is much faster to call
include? on - significant since include will get called n times.
We still end up double-reporting invalid dates, but that's no big deal.
=> Validation error for duplicate dates

README.md, lib/tasks/assets.rake
Suggested by @nevans as a fix for the build issue described in 5c0fa04
Basically the issue is that we need js to be available before the CSS
build, since the CSS bundle refers to files in node_modules.
This is currently being fixed by adding a node buildpack before the Ruby
buildpack, but that feels like overkill and shouldn't be required - it
also adds a little time to the build since it installs node and yarn (?)
rather than using the system versions (which I think will almost always
be enough for this project?), despite the warnings from Heroku in the
build log:
Installing a default version (1.22.19) of Yarn
This version is not pinned and can change over time, causing unexpected failures.
Heroku recommends placing the `heroku/nodejs` buildpack in front of the `heroku/ruby`
buildpack as …
=> Declare CSS build dependency: javascript:install

app/concerns/frequency.rb, app/controllers/occasional_events_controller.rb, app/models/event.rb, spec/forms/create_event_form_spec.rb, spec/services/socials_listings_integration_spec.rb
All new events are weekly (frequency 1) or occasional (frequency 0).
There are still events with a frequency of 2, 4 or more, but they can't
be saved without changing the frequency.
I guess previously we've been assuming that any event with dates must be
occasional, and that's hopefully true, but this change makes things more
explicit, and in any case, if an event is weekly and has dates, that
should be considered invalid data.
=> Refactor: occasional means frequency == 0

Gemfile, Gemfile.lock, spec/system/admins_can_clear_the_cache_spec.rb, spec/system/editors_can_disable_account_spec.rb, spec/system/editors_can_login_spec.rb
I know some of the matchers are buggy, and generally I'm no longer a fan of the approach. I don't think it's worth the cost of an extra dependency.
=> Remove elabs-matchers gem

app/controllers/robots_controller.rb, app/views/robots/index.text.erb, config/routes.rb, spec/requests/robots_spec.rb
We get requests form bots for sitemaps at different URLs sometimes.
Let's mitigate that by telling them where to expect to find it.
The challenge is that we need a different URL for London and Bristol, so
to support this, the robots txt needs to be dynamic, but let's ensure
that it's cached and publicly cacheable by intermediate proxies
(whatever those are).
=> Include sitemap in Robots.txt

config/routes.rb, spec/requests/sitemap_spec.rb
We keep getting requests for these URLs from BingBot, despite what
Robots.txt says, so let's redirect them and save some space in our error
logging.
=> Redirect requests for sitemaps

app/controllers/robots_controller.rb, app/views/robots/index.text.erb, spec/requests/robots_spec.rb
We don't have a canonical URL on staging, but we still get bots hitting
it, so let's make sure the robots file still works.
=> Fix robots on staging

app/helpers/events_helper.rb, app/models/event.rb
These should definitely not be in the model since they're purely for
display. And actually 2 of the 3 aren't used.
=> Remove unused constants

app/models/event.rb, spec/models/event_spec.rb, spec/system/editors_can_edit_events_spec.rb
This feels enough: since the user is picking from a select box, not
entering a value, so they can't recover. For that reason it feels
appropriate to get an ArgumentError rather than a validation error.
Note that the change in the Audit logs in specs is because now day will
be saved as nil, while currently it's always stored as an empty string.
Not sure if it's a bad idea to have an enum where the keys and values
are the same, but I can't see a reason why.
=> Set an enum for Event#day

app/views/listings/_facebook_buttons.html.erb
Got some odd routing errors - maybe //connect means "use the scheme of
the main website when requesting this", and some browsers can't handle
that and were instead trying to request it as a relative URL? Using a
full URL feels better in any case:
https://developers.facebook.com/docs/plugins/share-button/#example
=> Update Facebook share button src url

config/initializers/locale.rb, config/locales/en.rb
In production we have
config.i18n.fallbacks = true
...which for some reason results in this getting passed as a second
parameter to the lambdas:
{:fallback_original_locale=>:en}
I guess because maybe we're not explicitly setting locale? Is Rails
automatically setting the locale based on the browser settings? Doesn't
entirely make sense.
Also set the available locales to :en - this is already how it is on
staging (not sure how - maybe heroku does it?), but locally _all_ the
locales seem to be available by default.
=> Fix Locale issues

spec/services/socials_listings_integration_spec.rb, spec/system/editors_can_create_events_spec.rb
Previously we weren't able to mark an event as cancelled when creating,
since cancellation looked for an existing SwingDate record (?). Now that
we're using EventInstances we can take a more direct approach.
=> Update specs: cancel on create is now supported

config/environments/test.rb, spec/system/organisers_can_edit_events_spec.rb
This renders errors in test in the same way that they are in production,
so we can test in a more natural way. I'm surprised there's only one
example, but this still feels like the right way to go.
=> Use show_exceptions = :rescuable

app/javascript/controllers/flash_controller.js, app/javascript/controllers/index.js, app/views/shared/_flash.html.erb
This is particularly significant for the external events form: since 
there's no redirect, the flash doesn't otherwise disappear, so there's no
feedback that updates happened after the first one.
=> Flashes disappear after 3 seconds

.env.example, app/views/listings/_facebook_buttons.html.erb, app/views/listings/_navigation.html.erb
This doesn't seem to actually fix the Facebook like button (it breaks in
Chrome because of an issue with iFrames?) but it renders the same thing
in a much more terse way.
Switch to the button layout: button-count incorrectly reports 1.1k
people have liked, but actually it's more like 5k
=> Update Facebook like code

Gemfile, Gemfile.lock
Now we don't need to use master
=> Upgrade capybara to version with new headless

app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/auth_response.rb, app/models/login_session.rb, app/views/users/show.html.erb, lib/omniauth_test_response_builder.rb, spec/lib/omniauth_test_response_builder_spec.rb, spec/models/auth_response_spec.rb, spec/models/login_session_spec.rb, spec/system/editors_can_login_spec.rb
This isn't really useful, but it verifies that we have a 60 day token, so
Omniauth is indeed dealing with exchanging the initial short-lived auth
token for a longer lived token.
=> Show facebook auth token expiry on user page

app/controllers/users_controller.rb, app/presenters/access_token_expiry.rb, app/views/users/show.html.erb, spec/presenters/access_token_expiry_spec.rb, spec/system/editors_can_login_spec.rb
This is not entirely accurate: in the 0 case, we know that the token
will expire within 24 hours of now, which could be today or tomorrow.
We could make this more accurate by getting the actual Date objects
associated with these timestamps and comparing those, but I'm not sure
it's worth it? The nice thing about just doing numeric comparisons is
that this object is nice and simple and doesn't need to know about time
zone.
=> Display FB access token expiry in words

app/forms/edit_event_form.rb, app/views/events/_form.html.erb, spec/forms/edit_event_form_spec.rb, spec/system/editors_can_edit_events_spec.rb
This isn't allowed, so we get an unhandled error if it happens. Prevent
it by not showing the monthly box if it's a persisted weekly class.
https://app.rollbar.com/a/swingoutlondon/fix/item/SOLDN/178
https://app.rollbar.com/a/swingoutlondon/fix/item/SOLDN/179
=> Fix: don't allow editing freq for weekly class

config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, lib/filtering_logger_formatter.rb
The HTTP gem logs EVERYthing, including bearer tokens.
This is maybe not an actual problem since currently we have log level as
info in production in order to not max out the limits on papertrail. But
I don't want to change that later and unexpectedly leak data.
The solution is to create a log formatter which wraps the normal basic
formatter and sanitises the message.
=> Filter HTTP logs

app/services/user_name.rb, spec/services/user_name_spec.rb
It's slow so we don't want to have to retrieve them every time we load
this page.
=> Cache names from the Facebook graph API

app/assets/stylesheets/application_cms.scss, app/assets/stylesheets/cms/_users.scss, app/views/admin/users/index.html.erb
Like a table at larger sizes, like a list of blocks at mobile size.
This probably isn't best practice - having two sets of heading/label
elements, but it's good enough for us admins.
=> Styling of the user list

app/assets/stylesheets/cms/_forms.scss, app/views/events/_organiser_link.html.erb
This kind of breaks the layout on mobile
=> Fix: stop organiser link input from overflowing

spec/support/auth_helper.rb, spec/system/admins_can_clear_the_cache_spec.rb, spec/system/admins_can_manage_users_spec.rb, spec/system/admins_can_view_an_audit_log_spec.rb, spec/system/editors_can_copy_organiser_link_spec.rb, spec/system/editors_can_create_events_spec.rb, spec/system/editors_can_create_organisers_spec.rb, spec/system/editors_can_create_venues_spec.rb, spec/system/editors_can_delete_events_spec.rb, spec/system/editors_can_delete_organisers_spec.rb, spec/system/editors_can_delete_venues_spec.rb, spec/system/editors_can_edit_events_spec.rb, spec/system/editors_can_edit_organisers_spec.rb, spec/system/editors_can_edit_venues_spec.rb, spec/system/editors_can_list_events_spec.rb, spec/system/editors_can_list_occasional_events_spec.rb, spec/system/editors_can_navigate_spec.rb, spec/system/editors_can_see_associated_events_on_venues_spec.rb
Save about 5 seconds from the total suite time by not unnecessarily
logging in.
=> Skip login wherever possible

config/environments/production.rb
Only allow traffic to the canonical host:
https://prathamesh.tech/2019/09/02/dns-rebinding-attacks-protection-in-rails-6/
https://guides.rubyonrails.org/configuring.html#actiondispatch-hostauthorization
=> Protect against DNS rebinding attacks

app/javascript/maps/map.js
Google maps handles info windows near the edge of the page by scrolling
just enough that the whole info window is in view.
But it doesn't know about the map menu we have overlaying the left side
of the screen, so we need to do this manually:
1. get the coordinates from the click event - latLng is a property of
the click event:
https://developers.google.com/maps/documentation/javascript/reference/advanced-markers#AdvancedMarkerElement-Events
https://developers.google.com/maps/documentation/javascript/reference/map#MapMouseEvent
2. Wait for the info window to become visible:
https://developers.google.com/maps/documentation/javascript/reference/info-window#InfoWindow.visible
3. Now that it's visible we can get it's width, add half of that to
the offset, and pan so that the marker is within …
=> Ensure that map info windows are always visible

app/views/robots/index.text.erb
This is to allow it to review our access and hopefully to stop us
getting randomly disabled all the time.
Also fix indentation of the sitemap statement
=> Allow Facebook crawler to access login page

app/views/sessions/new.html.erb
This shows up as a required field:
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.swingoutlondon.co.uk%2Flogin
=> Add FB App ID to login page

spec/support/system/drivers.rb
The most recent versions of Chrome prompt the user to select a search
engine when opening the browser for the first time. This happens even in
tests, causing tests to fail with errors like "window failed to close
after 20 seconds"
To to disable the chrome search engine selection modal we need to define
a new driver, since this option doesn't seem to be used in the
selenium_chrome_headless driver (which is defined by Capybara).
If Capybara adds the --disable-search-engine-choice-screen option as a
default, we can delete this override.
=> Override Capybara selenium_chrome_headless driver

app/controllers/admin/users_controller.rb, app/models/role.rb, app/validators/numeric_string_validator.rb, app/views/admin/users/index.html.erb, config/locales/en.yml, spec/models/role_spec.rb, spec/system/admins_can_manage_users_spec.rb
We had an issue on production where Chris added "meli.rousseau" as the
Facebook ID. This is obviously incorrect since IDs are numeric strings,
but worse, this record couldn't be deleted - maybe because of how the
dot in the name was interpreted (user couldn't be found).
This can all be avoided by adding some validation.
=> Validate Facebook ID when creating user

.env.example, app/models/role.rb, app/presenters/users_listing.rb, config/initializers/facebook.rb, spec/system/admins_can_manage_users_spec.rb
Facebook very annoyingly require us to keep a test user account that
they can log into to verify that the site is legit.
However, for reasons I don't understand, the Graph API calls to fetch
its username fail, leading to errors every time we load the page.
Also someone deleted it by accident since it looks like just junk.
The solution is to special-case it and remove it from the page
completely.
=> Don't include the Facebook test user in list

spec/system/editors_can_edit_events_spec.rb
Previously the Audit records weren't getting created inside the Timecop
block.
The theory is that since I'm now on faster hardware, the spec exits the
timecop block before the server has finished responding, allowing the
Audit record to get created outside it (in regular clock time).
Adding an assertion forces the spec to wait until the server has
finished doing its thing.
I guess this was always incorrect, but it worked by accident due to slow
specs.
=> Fix issues with speedy specs

spec/system/editors_can_copy_organiser_link_spec.rb
The issue here is that on fast hardware the spec evaluates before the
content has been copied to the clipboard.
We can fix this by waiting for the "Copied" text to show
=> Fix clipboard specs

app/concerns/urls.rb, app/forms/create_event_form.rb, app/forms/edit_event_form.rb, app/models/event.rb, lib/urls.rb, spec/forms/create_event_form_spec.rb, spec/forms/edit_event_form_spec.rb, spec/models/event_spec.rb
A really long URL, used as the title of a class, broke the layout.
=> Validate title and URL length

app/assets/stylesheets/cms/_forms.scss, app/views/events/_form.html.erb, app/views/external_events/edit.html.erb, spec/system/organisers_can_edit_events_spec.rb
I don't think there's any point? This date never gets used for occasional
events? It's legacy from when we used to check for whether an event was
"active" or not.
=> Don't let occasional organisers set last date

app/forms/create_event_form.rb, app/forms/edit_event_form.rb, app/views/events/_form.html.erb, spec/system/editors_can_create_events_spec.rb
1. Start a new event
2. Select Weekly class
3. click save (get a validation error)
At this point we were in a state we hadn't accounted for: the "When?"
section is shown, but not as a direct result of clicking an event type.
As a result we were showing both frequency options, allowing the user to
select "occasional" and result in an error.
We fix this by applying a hidden class to the frequency section based on
event type.
=> Fix: don't show frequency for weekly class on error

app/assets/stylesheets/website/_map.scss, app/javascript/controllers/map_controller.js, app/javascript/maps/map.js, app/models/maps/markers.rb, app/views/maps/_map_info_address.html.erb, spec/system/users_can_see_a_map_spec.rb
This is now a first-class thing, and the windows look a lot better with the
title in the header field.
=> Move venue name into info window header
